# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a95c86aecc7bd1b3da712062aadfa46037309885fd75dbae2dbfc379e6fdee74725f610f15418aa0a8b8c3d844a402c19c95369f444f5b37ff4c565a11ae9857

test:
  secret_key_base: 7d8ece0c5fcb6ed5c7b3ac31a3bb8c39d5c22a1e65e42052be26022c17a33ed991e0284bad69e6a0749a23bd156d32b8a8225882e48aa411271253036c7de0e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
